theme: jekyll-theme-cayman
title: Terralia - Documentación
description: Documentación técnica y funcional del proyecto Terralia
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
